### ISSUE TITLE
SolrCloud Core metrics are not compatible with Solr 7.3 version

### ISSUE THREAD

**Issue by jpcarregosa-fixeads** [signalfx/collectd-solr#3]
Core metrics were not available on SIgnalFX.

After troubleshooting was discovered that the problem is on the internal replica naming.

For example metric for numDocs are on the path:
Solr 6.6
u'metrics.solr.core.xpto_geo_01.shard1.replica11.SEARCHER.searcher.numDocs',
Solr 7.3
u'metrics.solr.core.xpto_01.shard1.replica_n11.SEARCHER.searcher.numDocs',

To allow solr 7 to work function parse_corename was changed to this:
```
 def parse_corename(collection, shard, core_val):
     split_core_val = re.search("^.*_(.*)_(.*)$", core_val).group(1,2)
     replica = "_".join(split_core_val)
     core = "{0}.{1}.{2}".format(collection, shard, replica)

     return core
```

**Comment by dloucasfx** [comment]
Fixed in https://github.com/signalfx/collectd-solr/pull/5
